// @generated by protoc-gen-connect-es v0.13.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file schema/chores.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Chore, ChoreResponse, Empty } from "./chores_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ChoreService
 */
export declare const ChoreService: {
  readonly typeName: "ChoreService",
  readonly methods: {
    /**
     * @generated from rpc ChoreService.GetChores
     */
    readonly getChores: {
      readonly name: "GetChores",
      readonly I: typeof Empty,
      readonly O: typeof ChoreResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ChoreService.AddChore
     */
    readonly addChore: {
      readonly name: "AddChore",
      readonly I: typeof Chore,
      readonly O: typeof ChoreResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ChoreService.UpdateChore
     */
    readonly updateChore: {
      readonly name: "UpdateChore",
      readonly I: typeof Chore,
      readonly O: typeof ChoreResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

